# embed_monitor_page.py
# PlatformIO pre-build script: gzips tools/Eaglehagen_Serial_Monitor.html into
# include/MonitorPage.h so the web server can offer the PC monitor page for download.
# The HTML file in tools/ stays the single source; the header is generated (see .gitignore).

import gzip
import os

Import("env")  # noqa: F821 (provided by PlatformIO)

project_dir = env.subst("$PROJECT_DIR")  # noqa: F821
src = os.path.join(project_dir, "tools", "Eaglehagen_Serial_Monitor.html")
dst = os.path.join(project_dir, "include", "MonitorPage.h")

with open(src, "rb") as f:
    html = f.read()
gz = gzip.compress(html, compresslevel=9, mtime=0)  # mtime=0: identical output for identical input

lines = []
for i in range(0, len(gz), 16):
    lines.append("  " + ", ".join("0x%02x" % b for b in gz[i:i + 16]) + ",")

header = (
    "#ifndef MONITOR_PAGE_H\n"
    "#define MONITOR_PAGE_H\n\n"
    "#include <Arduino.h>\n\n"
    "// GENERATED by scripts/embed_monitor_page.py from tools/Eaglehagen_Serial_Monitor.html\n"
    "// Do not edit. Original size: %d bytes, gzip size: %d bytes\n\n"
    "const uint8_t PROGMEM MONITOR_PAGE_GZ[] = {\n%s\n};\n"
    "const unsigned int MONITOR_PAGE_GZ_LEN = %d;\n\n"
    "#endif // MONITOR_PAGE_H\n"
) % (len(html), len(gz), "\n".join(lines), len(gz))

old = None
if os.path.exists(dst):
    with open(dst, "r", encoding="ascii") as f:
        old = f.read()
if old != header:
    with open(dst, "w", encoding="ascii", newline="\n") as f:
        f.write(header)
    print("MonitorPage.h regenerated (%d -> %d bytes gzip)" % (len(html), len(gz)))
